@ECHO OFF
REM BFCPEOPTIONSTART
REM Advanced BAT to EXE Converter www.BatToExeConverter.com
REM BFCPEEXE=C:\Users\Nathaniel\Downloads\GOLauncher.exe
REM BFCPEICON=C:\Users\Nathaniel\Desktop\if-adventure-map-2913095_88801.ico
REM BFCPEICONINDEX=-1
REM BFCPEEMBEDDISPLAY=0
REM BFCPEEMBEDDELETE=1
REM BFCPEADMINEXE=0
REM BFCPEINVISEXE=1
REM BFCPEVERINCLUDE=1
REM BFCPEVERVERSION=0.0.0.1
REM BFCPEVERPRODUCT=GOLauncher
REM BFCPEVERDESC=Launcher for Grand Odyssey
REM BFCPEVERCOMPANY=AtroxFN
REM BFCPEVERCOPYRIGHT=GNU 3.0 License
REM BFCPEWINDOWCENTER=1
REM BFCPEDISABLEQE=0
REM BFCPEWINDOWHEIGHT=25
REM BFCPEWINDOWWIDTH=80
REM BFCPEWTITLE=GOLauncher
REM BFCPEOPTIONEND
@echo off

call Odyssey_data\lib\gameCore\GrandOdyssey.bat